import { describe, expect, it } from '@jest/globals';
import {
  escapeHtml,
  isOneDriveUrl,
  normalizePageUrlInput,
  sanitizeExternalIframeUrl,
  sanitizeEmbeddedHtml,
  sanitizeGoogleEmbedUrl,
  sanitizeHttpUrl,
  sanitizeImageUrl,
  sanitizeLinkUrl,
  sanitizeNotionHtml,
  sanitizeOneDriveEmbedUrl,
  sanitizeVideoEmbedUrl
} from '../../../js/utils/htmlSecurity.js';

const SIGNED_IMAGE_URL = 'https://assets.example.com/private/map.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=test%2F20260722%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Signature=abc123&X-Amz-Expires=3600';
const ONEDRIVE_EMBED_URL = 'https://1drv.ms/w/c/8480b8199298dc6a/IQSJYPNDDhaHR6l68QswlHANAfzkMRJ6-BOy2ZMGhr-_BsM?em=2';

function fragmentFrom(html) {
  const template = document.createElement('template');
  template.innerHTML = html;
  return template.content;
}

describe('HTML security helpers', () => {
  it('escapes every character that can break out of HTML text or quoted attributes', () => {
    expect(escapeHtml(`<script data-value="'&">alert(1)</script>`)).toBe(
      '&lt;script data-value=&quot;&#039;&amp;&quot;&gt;alert(1)&lt;/script&gt;'
    );
  });

  it.each([
    'javascript:alert(1)',
    'data:text/html,<script>alert(1)</script>',
    'vbscript:msgbox(1)'
  ])('rejects the executable URL protocol in %s', unsafeUrl => {
    expect(sanitizeHttpUrl(unsafeUrl)).toBe('');
    expect(sanitizeLinkUrl(unsafeUrl)).toBe('');
  });

  it('preserves an HTTPS signed URL byte-for-byte', () => {
    expect(sanitizeHttpUrl(SIGNED_IMAGE_URL)).toBe(SIGNED_IMAGE_URL);
    expect(sanitizeLinkUrl(SIGNED_IMAGE_URL)).toBe(SIGNED_IMAGE_URL);
  });

  it('accepts raster-only data URLs in image contexts', () => {
    const raster = 'data:image/png;base64,QUJDRA==';
    expect(sanitizeImageUrl(raster)).toBe(raster);
    expect(sanitizeImageUrl('data:image/svg+xml;base64,PHN2Zz48L3N2Zz4=')).toBe('');
    expect(sanitizeImageUrl('data:text/html;base64,PHNjcmlwdD48L3NjcmlwdD4=')).toBe('');
  });

  it('only accepts the video and Google embed endpoints generated by GM Vault', () => {
    expect(sanitizeVideoEmbedUrl('https://www.youtube.com/embed/AbCdEf012_-?autoplay=1'))
      .toBe('https://www.youtube.com/embed/AbCdEf012_-?autoplay=1');
    expect(sanitizeVideoEmbedUrl('https://player.vimeo.com/video/123456?autoplay=1'))
      .toBe('https://player.vimeo.com/video/123456?autoplay=1');
    expect(sanitizeGoogleEmbedUrl('https://docs.google.com/document/d/doc_123/preview'))
      .toBe('https://docs.google.com/document/d/doc_123/preview');
    expect(sanitizeGoogleEmbedUrl('https://drive.google.com/file/d/file_123/preview'))
      .toBe('https://drive.google.com/file/d/file_123/preview');

    expect(sanitizeVideoEmbedUrl('javascript:alert(1)')).toBe('');
    expect(sanitizeVideoEmbedUrl('https://vault.example/html/video-viewer.html?url=javascript:alert(1)')).toBe('');
    expect(sanitizeVideoEmbedUrl('https://youtube.com.evil.example/embed/AbCdEf012_-')).toBe('');
    expect(sanitizeGoogleEmbedUrl('https://docs.google.com.evil.example/document/d/x/preview')).toBe('');
  });

  it('accepts only official OneDrive Personal Embed URLs', () => {
    expect(isOneDriveUrl(ONEDRIVE_EMBED_URL)).toBe(true);
    expect(sanitizeOneDriveEmbedUrl(ONEDRIVE_EMBED_URL)).toBe(ONEDRIVE_EMBED_URL);
    expect(sanitizeOneDriveEmbedUrl('https://onedrive.live.com/embed?resid=ABC123&authkey=DEF456'))
      .toBe('https://onedrive.live.com/embed?resid=ABC123&authkey=DEF456');

    expect(sanitizeOneDriveEmbedUrl(
      'https://1drv.ms/w/c/8480b8199298dc6a/IQCJYPNDDhaHR6l68QswlHANAVALRHpMyZHEZNXc0y-nt6Q'
    )).toBe('');
    expect(isOneDriveUrl('https://1drv.ms.evil.example/w/c/file?em=2')).toBe(false);
    expect(sanitizeOneDriveEmbedUrl(
      'https://1drv.ms.evil.example/w/c/8480b8199298dc6a/file?em=2'
    )).toBe('');
  });

  it('extracts the safe src when the complete OneDrive iframe is pasted', () => {
    const iframe = `<iframe src="${ONEDRIVE_EMBED_URL}" width="476px" height="288px" frameborder="0" title="PowerPoint Viewer">fallback</iframe>`;

    expect(normalizePageUrlInput(iframe)).toBe(ONEDRIVE_EMBED_URL);
    expect(normalizePageUrlInput(ONEDRIVE_EMBED_URL)).toBe(ONEDRIVE_EMBED_URL);
    expect(normalizePageUrlInput('<iframe src="https://evil.example/embed"></iframe>')).toBe('');
    expect(normalizePageUrlInput('<iframe src="javascript:alert(1)"></iframe>')).toBe('');
  });

  it('rejects same-origin and non-HTTPS iframe URLs', () => {
    expect(sanitizeExternalIframeUrl(
      'https://vault.example/html/video-viewer.html?url=javascript%3Aalert(1)',
      'https://vault.example'
    )).toBe('');
    expect(sanitizeExternalIframeUrl('http://embed.example/map', 'https://vault.example')).toBe('');
    expect(sanitizeExternalIframeUrl('https://embed.example/map', 'https://vault.example'))
      .toBe('https://embed.example/map');
  });

  it('keeps generic embeds on an opaque sandbox origin', () => {
    const fragment = fragmentFrom(sanitizeNotionHtml(`
      <iframe class="generic" src="https://embed.example/map"></iframe>
      <iframe class="youtube" src="https://www.youtube.com/embed/AbCdEf012_-"></iframe>
      <iframe class="onedrive" src="${ONEDRIVE_EMBED_URL}"></iframe>
    `));
    const genericSandbox = fragment.querySelector('.generic').getAttribute('sandbox');
    const youtubeSandbox = fragment.querySelector('.youtube').getAttribute('sandbox');
    const oneDriveSandbox = fragment.querySelector('.onedrive').getAttribute('sandbox');

    expect(genericSandbox).toContain('allow-scripts');
    expect(genericSandbox).not.toContain('allow-same-origin');
    expect(youtubeSandbox).toContain('allow-same-origin');
    expect(oneDriveSandbox).toContain('allow-same-origin');
  });
});

describe('sanitizeNotionHtml', () => {
  it('drops executable elements, handlers, srcdoc and executable URLs', () => {
    const sanitized = sanitizeNotionHtml(`
      <script>globalThis.__scriptXss = true</script>
      <svg onload="globalThis.__svgXss = true"><circle></circle></svg>
      <form action="https://evil.example/collect"><input name="secret"><button>Send</button></form>
      <a class="unsafe-link" href="javascript:alert(1)" onclick="alert(2)">unsafe link</a>
      <img class="unsafe-image" src="data:image/svg+xml,<svg onload=alert(1)>" onerror="alert(2)">
      <video class="unsafe-video" src="vbscript:msgbox(1)" poster="data:image/svg+xml,bad" oncanplay="alert(2)"></video>
      <iframe class="unsafe-frame" src="javascript:alert(1)" srcdoc="<script>alert(2)</script>"></iframe>
      <span class="unsafe-data"
            data-image-url="javascript:alert(1)"
            data-video-url="data:text/html,bad"
            data-mention-page-url="vbscript:msgbox(1)">data</span>
    `);
    const fragment = fragmentFrom(sanitized);

    expect(fragment.querySelector('script, svg, form')).toBeNull();
    expect(fragment.querySelector('.unsafe-frame')).toBeNull();
    expect(fragment.querySelector('.unsafe-link').hasAttribute('href')).toBe(false);
    expect(fragment.querySelector('.unsafe-image').hasAttribute('src')).toBe(false);
    expect(fragment.querySelector('.unsafe-video').hasAttribute('src')).toBe(false);
    expect(fragment.querySelector('.unsafe-video').hasAttribute('poster')).toBe(false);

    const unsafeData = fragment.querySelector('.unsafe-data');
    expect(unsafeData.hasAttribute('data-image-url')).toBe(false);
    expect(unsafeData.hasAttribute('data-video-url')).toBe(false);
    expect(unsafeData.hasAttribute('data-mention-page-url')).toBe(false);

    for (const element of fragment.querySelectorAll('*')) {
      const attributeNames = element.getAttributeNames().map(name => name.toLowerCase());
      expect(attributeNames.some(name => name.startsWith('on'))).toBe(false);
      expect(attributeNames).not.toContain('srcdoc');
    }
  });

  it('preserves the safe Notion structures and metadata needed by the UI', () => {
    const safeMentionUrl = 'https://www.notion.so/Secret-Room-123456781234123412341234567890ab';
    const sanitized = sanitizeNotionHtml(`
      <div class="notion-column-list" style=" --column-count : 3; " data-layout="columns">
        <span class="notion-mention notion-mention--link"
              data-mention-page-id="12345678-1234-1234-1234-1234567890ab"
              data-mention-page-name="Secret Room"
              data-mention-page-url="${safeMentionUrl}"
              role="button" tabindex="0">Secret Room</span>
        <table class="notion-table" data-table-id="table-1">
          <tbody><tr><th colspan="2">Heading</th></tr><tr><td>Value</td><td>Other</td></tr></tbody>
        </table>
        <details class="notion-toggle" open data-toggle-id="toggle-1">
          <summary>Map</summary>
          <img class="notion-image-clickable"
               src="${SIGNED_IMAGE_URL}"
               alt="Dungeon map"
               data-image-url="${SIGNED_IMAGE_URL}"
               data-image-kind="content"
               loading="eager">
        </details>
      </div>
    `);
    const fragment = fragmentFrom(sanitized);
    const columns = fragment.querySelector('.notion-column-list');
    const mention = fragment.querySelector('.notion-mention');
    const table = fragment.querySelector('table');
    const details = fragment.querySelector('details');
    const image = fragment.querySelector('img');

    expect(columns.getAttribute('style')).toBe('--column-count: 3');
    expect(columns.dataset.layout).toBe('columns');
    expect(mention.dataset.mentionPageId).toBe('12345678-1234-1234-1234-1234567890ab');
    expect(mention.dataset.mentionPageName).toBe('Secret Room');
    expect(mention.dataset.mentionPageUrl).toBe(safeMentionUrl);
    expect(mention.getAttribute('role')).toBe('button');
    expect(table.dataset.tableId).toBe('table-1');
    expect(table.querySelectorAll('tr')).toHaveLength(2);
    expect(details.open).toBe(true);
    expect(details.dataset.toggleId).toBe('toggle-1');
    expect(image.getAttribute('src')).toBe(SIGNED_IMAGE_URL);
    expect(image.dataset.imageUrl).toBe(SIGNED_IMAGE_URL);
    expect(image.dataset.imageKind).toBe('content');
  });

  it('only preserves the constrained column-count style', () => {
    const fragment = fragmentFrom(sanitizeNotionHtml(`
      <div class="safe-columns" style="--column-count: 20"></div>
      <div class="unsafe-columns" style="--column-count: 21"></div>
      <div class="css-injection" style="--column-count: 3; background: url(javascript:alert(1))"></div>
      <span class="wrong-element" style="--column-count: 3"></span>
    `));

    expect(fragment.querySelector('.safe-columns').getAttribute('style')).toBe('--column-count: 20');
    expect(fragment.querySelector('.unsafe-columns').hasAttribute('style')).toBe(false);
    expect(fragment.querySelector('.css-injection').hasAttribute('style')).toBe(false);
    expect(fragment.querySelector('.wrong-element').hasAttribute('style')).toBe(false);
  });
});

describe('sanitizeEmbeddedHtml', () => {
  const RASTER_DATA_URL = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAB';

  it.each(['png', 'jpg', 'jpeg', 'gif', 'webp', 'bmp'])(
    'preserves data:image/%s base64 images in src and exporter metadata',
    mimeType => {
      const dataUrl = `data:image/${mimeType};base64,QUJDRA==`;
      const fragment = fragmentFrom(sanitizeEmbeddedHtml(`
        <div class="notion-image-container">
          <img class="notion-image-clickable"
               src="${dataUrl}"
               data-image-url="${dataUrl}"
               alt="Local map">
        </div>
      `));
      const image = fragment.querySelector('img');

      expect(image.getAttribute('src')).toBe(dataUrl);
      expect(image.getAttribute('data-image-url')).toBe(dataUrl);
      expect(image.getAttribute('alt')).toBe('Local map');
    }
  );

  it('preserves the exact safe inline-CSS combinations emitted by the Obsidian exporter', () => {
    const fragment = fragmentFrom(sanitizeEmbeddedHtml(`
      <div class="gallery-row" style="display: flex; gap: 16px; margin-bottom: 16px;"></div>
      <div class="gallery-cell" style="flex: 1; position: relative;"></div>
      <img class="gallery-image" src="${RASTER_DATA_URL}"
           style="width: 100%; height: auto; border-radius: 4px; object-fit: contain; background: #f5f5f5; cursor: pointer;">
      <div class="callout"
           style="background: #fef3c7; border-left: 3px solid #f59e0b; padding: 12px; margin: 16px 0; border-radius: 4px;"></div>
      <p class="callout-copy" style="margin: 0; color: #92400e;"></p>
    `));

    expect(fragment.querySelector('.gallery-row').getAttribute('style'))
      .toBe('display: flex; gap: 16px; margin-bottom: 16px');
    expect(fragment.querySelector('.gallery-cell').getAttribute('style'))
      .toBe('flex: 1; position: relative');
    expect(fragment.querySelector('.gallery-image').getAttribute('style'))
      .toBe('width: 100%; height: auto; border-radius: 4px; object-fit: contain; background: #f5f5f5; cursor: pointer');
    expect(fragment.querySelector('.callout').getAttribute('style'))
      .toBe('background: #fef3c7; border-left: 3px solid #f59e0b; padding: 12px; margin: 16px 0; border-radius: 4px');
    expect(fragment.querySelector('.callout-copy').getAttribute('style'))
      .toBe('margin: 0; color: #92400e');
  });

  it('removes SVG data images, executable markup and inline event handlers', () => {
    const fragment = fragmentFrom(sanitizeEmbeddedHtml(`
      <script>window.__embeddedXss = true</script>
      <img class="svg-plain"
           src="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg'><script>alert(1)</script></svg>"
           onerror="window.__embeddedXss = true">
      <img class="svg-base64"
           src="data:image/svg+xml;base64,PHN2ZyBvbmxvYWQ9J2FsZXJ0KDEpJz48L3N2Zz4="
           data-image-url="data:image/svg+xml;base64,PHN2Zz48L3N2Zz4=">
      <button onclick="window.__embeddedXss = true">Safe label</button>
    `));

    expect(fragment.querySelector('script')).toBeNull();
    expect(fragment.querySelector('.svg-plain').hasAttribute('src')).toBe(false);
    expect(fragment.querySelector('.svg-base64').hasAttribute('src')).toBe(false);
    expect(fragment.querySelector('.svg-base64').hasAttribute('data-image-url')).toBe(false);
    expect(fragment.querySelector('[onerror], [onclick]')).toBeNull();
    expect(fragment.querySelector('button').textContent).toBe('Safe label');
  });

  it('strips CSS url(), expression() and fixed positioning', () => {
    const fragment = fragmentFrom(sanitizeEmbeddedHtml(`
      <div class="url-css" style="background: url(javascript:alert(1)); color: #fff;"></div>
      <div class="expression-css" style="width: expression(alert(1)); color: #fff;"></div>
      <div class="fixed-css" style="position: fixed; color: #fff; top: 0; left: 0;"></div>
    `));

    expect(fragment.querySelector('.url-css').hasAttribute('style')).toBe(false);
    expect(fragment.querySelector('.expression-css').hasAttribute('style')).toBe(false);
    expect(fragment.querySelector('.fixed-css').getAttribute('style')).toBe('color: #fff');
    expect(fragment.querySelector('.fixed-css').getAttribute('style')).not.toMatch(/position|fixed|top|left/i);
  });
});
